apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spiskammerset-db-policy
  namespace: tbd
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 34.88.114.117/32
  podSelector:
    matchLabels:
      dbPolicyUser: spiskammersetbruker
  policyTypes:
    - Egress
