apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spiskammerset-opprydding-dev
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    periodSeconds: 1
  resources:
    limits:
      memory: 512Mi
  prometheus:
    path: /metrics
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  kafka:
    pool: {{kafkaPool}}
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{consumerGroupId}}
    - name: KAFKA_RESET_POLICY
      value: LATEST

