apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spiskammerset-opprydding-dev
  namespace: tbd
  labels:
    team: tbd
    dbPolicyUser: spiskammersetbruker
spec:
  image: {{image}}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    periodSeconds: 1
  resources:
    limits:
      memory: 512Mi
  prometheus:
    path: /metrics
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/cloudsql.client
  envFrom:
    - secret: google-sql-spiskammerset-spiskammerset-spiskammerset-o-5f7ab9e2
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spiskammerset-opprydding-v1
    - name: KAFKA_RESET_POLICY
      value: LATEST
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: "spiskammerset"

